version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=access_logs
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: access_logs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
