apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: flask-app:v4
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres-db"
            - name: DB_NAME
              value: "access_logs"
            - name: DB_USER
              value: "user"
            - name: DB_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
